export {default as LandingPage} from "./LandingPage"
export {default as Home} from "./Home"
export {default as AuthenticationForm} from "./AuthenticationForm"
export {default as Discover} from "./Discover"
export {default as Profile} from "./Profile"
